import { Helmet } from 'react-helmet-async'
import { Link } from 'wouter'
import { ArrowRight, ExternalLink, CheckCircle } from 'lucide-react'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'

const APP = 'https://app.procta.net'

const platforms = [
  {
    id: 'canvas',
    name: 'Canvas',
    logo: '📚',
    steps: [
      'Log in to your Canvas account as an Admin.',
      'Navigate to **Admin → Settings → Apps** (or **Account → Settings → Apps**).',
      'Click **+ App** and select **By Client ID** from the Configuration Type dropdown.',
      'Paste the Procta Client ID (provided during onboarding) and click **Submit**.',
      'After registration, click **Manage** → **Edit Placements** and add placements for **Course Navigation** and **Assignment Selection**.',
      'Open any course, click **Procta** in the course navigation menu, and verify that the tool loads correctly.',
    ],
    tip: 'For self-registration (dynamic), use the Auto-config URL below instead of Client ID. Canvas will fetch the configuration automatically.',
  },
  {
    id: 'moodle',
    name: 'Moodle',
    logo: '🎓',
    steps: [
      'Log in as a Moodle **Site Administrator**.',
      'Navigate to **Site Administration → Plugins → Activity Modules → External tool → Manage tools**.',
      'Click **Install LTI Advantage Tool** at the top of the page.',
      'In the **Tool URL** field, enter the Auto-config URL below and click **Add Legacy LTI** (Moodle will fetch the configuration automatically).',
      'Review the pre-filled settings, set **Default launch container** to **Existing window**, and click **Save**.',
      'After registration, click the **gear icon** next to Procta and select **Activate** to enable the tool across all courses.',
    ],
    tip: 'Ensure your Moodle server can reach app.procta.net. If behind a firewall, whitelist the domain.',
  },
  {
    id: 'blackboard',
    name: 'Blackboard',
    logo: '🖥️',
    steps: [
      'Log in to Blackboard as an **Administrator**.',
      'Navigate to **Admin Panel → LTI Tool Providers → Register LTI 1.3/Advantage Tool**.',
      'Enter **Procta** as the Tool Provider Name.',
      'Set **Initiate Login URL** to the Login Initiation URL below.',
      'Set **Tool Redirect URL(s)** to the Launch URL below.',
      'Set **JWKS URL** to the JWKS URL below.',
      'Under Tool Services, select: **AGS Line Item Service**, **AGS Result Service**, and **NRPS Membership Service**.',
      'Click **Submit** to complete registration.',
      'After registration, copy the **Client ID** generated by Blackboard and provide it to Procta support to complete the configuration.',
    ],
    tip: 'Blackboard\'s LTI 1.3 registration requires an admin account. Standard instructors cannot register tools.',
  },
]

const overview_items = [
  {
    title: 'Grade Passback (AGS)',
    desc: 'Procta automatically pushes scores back to the LMS gradebook after each exam. No manual data entry needed.',
  },
  {
    title: 'Roster Sync (NRPS)',
    desc: 'Student rosters stay in sync automatically. When you publish an exam to a course in your LMS, all enrolled students are available in Procta without manual import.',
  },
  {
    title: 'Deep Linking',
    desc: 'Instructors can select Procta exams directly from within their LMS course — no need to copy-paste links or switch between platforms.',
  },
  {
    title: 'Single Sign-On (OIDC)',
    desc: 'Students and instructors log in via their LMS credentials. No separate Procta account needed.',
  },
]

export default function LtiSetup() {
  return (
    <div className="min-h-screen bg-navy-950">
      <Helmet>
        <title>LTI 1.3 Integration Setup — Procta for Canvas, Moodle &amp; Blackboard</title>
        <meta name="description" content="Step-by-step guide to integrating Procta AI proctoring with Canvas, Moodle, and Blackboard via LTI 1.3. Grade passback, roster sync, and SSO setup." />
        <link rel="canonical" href="https://procta.net/lti-setup" />
        <meta property="og:title" content="LTI 1.3 Integration Setup — Procta" />
        <meta property="og:description" content="Connect Procta with your LMS in minutes. Supports Canvas, Moodle, and Blackboard via LTI 1.3 Advantage standards." />
        <meta property="og:url" content="https://procta.net/lti-setup" />
      </Helmet>

      <Navbar />

      {/* Hero */}
      <section className="pt-36 pb-16 md:pt-44 md:pb-20">
        <div className="mx-auto max-w-3xl px-6 text-center">
          <span className="label-mono text-accent">LMS Integration</span>
          <h1 className="mt-3 font-display text-4xl font-bold text-white md:text-5xl">
            Connect Procta with your LMS
          </h1>
          <p className="mx-auto mt-4 text-lg text-slate-400">
            Procta supports <strong className="text-white">Canvas</strong>,{' '}
            <strong className="text-white">Moodle</strong>, and{' '}
            <strong className="text-white">Blackboard</strong> via the LTI 1.3 Advantage
            standard. Grade passback, roster sync, deep linking, and SSO — all included.
          </p>
        </div>
      </section>

      {/* Configuration URLs */}
      <section className="pb-8">
        <div className="mx-auto max-w-3xl px-6">
          <div className="rounded-2xl border border-white/[0.06] bg-white/[0.02] p-6 md:p-8">
            <h2 className="font-display text-xl font-bold text-white">Your Configuration URLs</h2>
            <p className="mt-2 text-sm text-slate-400">Use these URLs during LTI tool registration in your LMS.</p>
            <div className="mt-6 space-y-4">
              {[
                { label: 'Auto-config URL', url: `${APP}/lti/config` },
                { label: 'Login Initiation URL', url: `${APP}/lti/login` },
                { label: 'Launch / Redirect URL', url: `${APP}/lti/launch` },
                { label: 'Public JWKS URL', url: `${APP}/lti/jwks` },
                { label: 'Deep Linking URL', url: `${APP}/lti/deeplink` },
              ].map(item => (
                <div key={item.label} className="flex flex-col sm:flex-row sm:items-center gap-2">
                  <span className="text-sm font-medium text-slate-300 w-44 shrink-0">{item.label}</span>
                  <code className="flex-1 rounded-lg bg-navy-800 px-4 py-2.5 text-xs font-mono text-accent-light break-all select-all">
                    {item.url}
                  </code>
                  <button
                    onClick={() => { navigator.clipboard.writeText(item.url); }}
                    className="shrink-0 rounded-lg border border-white/10 bg-white/[0.03] px-3 py-2 text-xs text-slate-400 hover:text-white transition-colors cursor-pointer"
                  >
                    Copy
                  </button>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Platform tabs */}
      <section className="py-12">
        <div className="mx-auto max-w-4xl px-6">
          <h2 className="font-display text-2xl font-bold text-white text-center md:text-3xl">
            Setup guides by platform
          </h2>

          <div className="mt-10 space-y-10">
            {platforms.map(p => (
              <div key={p.id} className="rounded-2xl border border-white/[0.06] bg-white/[0.02] overflow-hidden">
                <div className="border-b border-white/[0.06] bg-white/[0.01] px-6 py-5">
                  <div className="flex items-center gap-3">
                    <span className="text-2xl">{p.logo}</span>
                    <h3 className="font-display text-lg font-bold text-white">{p.name}</h3>
                  </div>
                </div>
                <div className="px-6 py-6">
                  <ol className="space-y-5">
                    {p.steps.map((step, i) => (
                      <li key={i} className="flex gap-4">
                        <span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-accent/10 text-xs font-bold text-accent-light">
                          {i + 1}
                        </span>
                        <span className="text-sm leading-relaxed text-slate-300 [&_strong]:text-white [&_strong]:font-semibold">
                          <span dangerouslySetInnerHTML={{ __html: step.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>') }} />
                        </span>
                      </li>
                    ))}
                  </ol>
                  {p.tip && (
                    <div className="mt-6 rounded-xl border border-accent/20 bg-accent/[0.04] px-4 py-3">
                      <p className="text-xs leading-relaxed text-accent-light">
                        <strong className="text-accent-light">💡 Tip:</strong> {p.tip}
                      </p>
                    </div>
                  )}
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* What it gives you */}
      <section className="py-16 bg-navy-900/30">
        <div className="mx-auto max-w-4xl px-6">
          <h2 className="font-display text-2xl font-bold text-white text-center md:text-3xl">
            What LTI integration gives you
          </h2>
          <div className="mt-10 grid gap-6 sm:grid-cols-2">
            {overview_items.map(item => (
              <div key={item.title} className="rounded-xl border border-white/[0.06] bg-white/[0.02] p-6">
                <div className="mb-3 flex h-8 w-8 items-center justify-center rounded-lg bg-accent/10">
                  <CheckCircle size={18} className="text-accent-light" />
                </div>
                <h3 className="mb-1.5 text-sm font-semibold text-white">{item.title}</h3>
                <p className="text-sm leading-relaxed text-slate-400">{item.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Troubleshooting */}
      <section className="py-16">
        <div className="mx-auto max-w-3xl px-6">
          <h2 className="font-display text-2xl font-bold text-white text-center md:text-3xl">
            Troubleshooting
          </h2>
          <div className="mt-10 space-y-6">
            {[
              {
                q: 'The tool doesn\'t appear in my course after registration',
                a: 'Ensure the tool status is set to "Active" or "Approved" in your LMS admin panel. Some LMS platforms (like Moodle) require a separate activation step after registration.',
              },
              {
                q: 'Students get a "Tool not found" error when launching Procta',
                a: 'Verify that the LTI tool is assigned to the correct course. In Canvas, check Course Navigation placements. In Moodle, ensure the tool is set to "Show" in course-level settings.',
              },
              {
                q: 'Grades are not syncing back to the gradebook',
                a: 'Confirm that AGS (Grade Passback) is enabled in your LTI tool configuration. In Canvas, ensure the Line Item and Result scopes are checked during registration.',
              },
              {
                q: 'Is Google Classroom supported?',
                a: 'Yes — Procta now has a native Google Classroom integration via the Google Classroom API. Teachers can connect their Google account, sync course rosters, link exams to courses, and push grades back to Classroom. It uses a different integration model than LTI 1.3 (since Google Classroom does not fully support LTI 1.3). Go to Tools → Google Classroom in your Procta dashboard to set it up.',
              },
              {
                q: 'Can I use Procta without LTI?',
                a: 'Yes. LTI integration is optional. You can use Procta as a standalone platform via the web dashboard — invite students by email or access code without connecting to any LMS.',
              },
            ].map((item, i) => (
              <details key={i} className="group rounded-xl border border-white/[0.06]">
                <summary className="flex cursor-pointer list-none items-center justify-between px-5 py-4 text-sm font-medium text-white transition-colors hover:text-accent-light">
                  {item.q}
                  <ArrowRight size={14} className="shrink-0 text-slate-500 transition-transform group-open:rotate-90" />
                </summary>
                <p className="px-5 pb-4 text-sm leading-relaxed text-slate-400">{item.a}</p>
              </details>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-16 md:py-24 border-t border-white/[0.06]">
        <div className="mx-auto max-w-2xl px-6 text-center">
          <h2 className="font-display text-3xl font-bold text-white md:text-4xl">
            Ready to integrate Procta with your LMS?
          </h2>
          <p className="mt-4 text-lg text-slate-400">
            We'll help you set up the integration and run your first proctored exam.
          </p>
          <div className="mt-8 flex flex-col items-center gap-4 sm:flex-row sm:justify-center">
            <Link
              to="/signup"
              className="inline-flex items-center gap-2 rounded-xl bg-accent-dark px-7 py-3.5 text-sm font-semibold text-white glow-btn no-underline hover:bg-accent"
            >
              Start Free Trial
              <ArrowRight size={16} />
            </Link>
            <a
              href={`${APP}/dashboard`}
              className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/[0.03] px-7 py-3.5 text-sm font-semibold text-slate-300 transition-all hover:border-accent/30 no-underline"
              target="_blank"
              rel="noopener noreferrer"
            >
              Log In to Dashboard
              <ExternalLink size={14} />
            </a>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  )
}
