import { Link } from 'react-router-dom'
import { ArrowLeft } from 'lucide-react'
import Footer from '../components/Footer'

export default function Terms() {
  return (
    <div className="min-h-screen bg-navy-950">
      <div className="mx-auto max-w-3xl px-6 pt-24 pb-16">
        <Link to="/" className="mb-8 inline-flex items-center gap-2 text-sm text-slate-500 transition-colors hover:text-white no-underline">
          <ArrowLeft size={16} />
          Back to home
        </Link>

        <h1 className="font-display text-3xl font-bold text-white md:text-4xl">Terms of Service</h1>
        <p className="mt-2 text-sm text-slate-500">Last updated: April 2026</p>

        <div className="mt-10 space-y-8 text-sm leading-relaxed text-slate-400">
          <section>
            <h2 className="mb-3 text-lg font-semibold text-white">1. Acceptance of Terms</h2>
            <p>
              By accessing or using Procta's services, you agree to be bound by these Terms of Service.
              If you are using the service on behalf of an institution, you represent that you have the
              authority to bind that institution to these terms.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-white">2. Service Description</h2>
            <p>
              Procta provides AI-powered exam proctoring software, including a secure desktop browser,
              real-time monitoring, risk scoring, and administrative dashboards. The service is designed
              to assist institutions in maintaining exam integrity.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-white">3. User Responsibilities</h2>
            <p>
              Institutions are responsible for informing students about the use of proctoring software,
              obtaining necessary consent, and ensuring compliance with applicable privacy regulations.
              Users must not attempt to circumvent, reverse-engineer, or interfere with the proctoring system.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-white">4. AI-Assisted Decisions</h2>
            <p>
              Procta's risk scores and violation logs are generated by AI models and are intended as
              decision-support tools, not final judgments. Institutions retain full authority over academic
              integrity decisions. We recommend human review of flagged sessions before taking action.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-white">5. Availability</h2>
            <p>
              We strive for high availability but do not guarantee uninterrupted service. Scheduled
              maintenance will be communicated in advance. We are not liable for disruptions caused
              by factors outside our control.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-white">6. Limitation of Liability</h2>
            <p>
              Procta is provided "as is" without warranty of any kind. We are not liable for any indirect,
              incidental, or consequential damages arising from the use of our services, including but not
              limited to academic decisions made based on AI-generated reports.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-white">7. Contact</h2>
            <p>
              For questions about these terms, contact us at{' '}
              <a href="mailto:legal@procta.net" className="text-accent-light hover:text-white no-underline">
                legal@procta.net
              </a>.
            </p>
          </section>
        </div>
      </div>
      <Footer />
    </div>
  )
}
